const STORE = "celebra-hidrogest-v1";
const DEFAULT_PASSWORD = "celebra2026";
const seed = [
  ["Altamir Teixeira da Gama","1967-06-04"],["Alvimar","1983-06-11"],["Anna Paula","1991-11-26"],["Antonio Augusto","1988-06-21"],["Antônio Castro Neto","1967-05-23","Operações","assets/castro.jpg"],["Antonio Jose Machado","2023-06-15"],["Arthur Souza","2006-03-13"],["Carlos","2005-08-28"],["Dieyme Junior","2005-07-07"],["Douglas Maximiliano","1993-06-02"],["Glayson Alves de Jesus","1975-04-29"],["Gustavo Henrique da Silva Queiroz","1995-10-25"],["João Pedro","1999-01-17"],["Kellly",null],["Leonardo Gurgel","1986-06-29"],["Luis Felipe","2001-10-21"],["Mariane Rodrigues","1989-09-14"],["Mariê",null],["Michel Aguiar de Oliveira","1983-01-22"],["Miqueias Palmeira","2004-05-12"],["Paula","1978-11-18"],["Paulo","1993-01-24"],["Rafael Pereira","1989-09-17"],["Rogerio","2004-10-23"],["Ronaldo Adriano Raimundo","1977-12-01"],["Rosangela","1955-01-21"],["Thiago Gurgel","1990-01-14"],["Thiago Souto","1998-05-07"],["Victor Ibrahim","1990-11-06"],["Wlman de Oliveira","1987-06-04"]
].map((r,i)=>({id:`p${i+1}`,name:r[0],birthday:r[1],team:r[2]||"",photo:r[3]||"",message:"",photoStatus:r[3]?"ready":"pending"}));
let state = JSON.parse(localStorage.getItem(STORE) || "null") || { people:seed, password:DEFAULT_PASSWORD, messages:{birthday:"Feliz aniversário, {nome}! Que seu novo ciclo seja cheio de realizações e bons momentos.", recognition:"Parabéns, {nome}, por mais esta conquista. Seu trabalho faz diferença."} };
let editingId = null, photoMode = "link";
const $ = s => document.querySelector(s);
const esc = s => String(s||"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[c]));
function save(){localStorage.setItem(STORE,JSON.stringify(state));}
function initials(name){return name.split(" ").filter(Boolean).slice(0,2).map(n=>n[0]).join("").toUpperCase();}
function asPhoto(url){if(!url)return "";const match=url.match(/(?:\/d\/|id=)([\w-]{15,})/);return match?`https://drive.google.com/uc?export=view&id=${match[1]}`:url;}
function birthdayParts(date){if(!date)return null;const [,m,d]=date.match(/\d{4}-(\d{2})-(\d{2})/)||[];return m&&d?{m:+m,d:+d}:null;}
function nextOccurrence(p){const x=birthdayParts(p.birthday);if(!x)return null;const n=new Date(), y=n.getFullYear();let due=new Date(y,x.m-1,x.d,12);if(due<new Date(n.getFullYear(),n.getMonth(),n.getDate()))due.setFullYear(y+1);return due;}
function daysUntil(p){const d=nextOccurrence(p);if(!d)return 9999;return Math.ceil((d-new Date())/86400000);}
function dateLabel(d){return d.toLocaleDateString("pt-BR",{day:"2-digit",month:"short"}).replace(".","");}
function status(p){if(!p.birthday)return "Data pendente";if(!p.photo)return "Foto pendente";return "Completo";}
function personImage(p,cls="avatar"){return p.photo?`<img class="${cls}" src="${esc(asPhoto(p.photo))}" alt="${esc(p.name)}" onerror="this.remove()">`:`<div class="${cls}">${initials(p.name)}</div>`;}
function renderDashboard(){const soon=state.people.filter(p=>p.birthday).sort((a,b)=>daysUntil(a)-daysUntil(b)).slice(0,5);const pending=state.people.filter(p=>!p.birthday||!p.photo);const thisWeek=soon.filter(p=>daysUntil(p)<=7);$("#dashboardView").innerHTML=`<div class="dashboard-grid"><section class="card hero-card"><p class="eyebrow">PRÓXIMA CELEBRAÇÃO</p><h2>${soon[0]?`Faltam ${daysUntil(soon[0])} dias para celebrar ${esc(soon[0].name.split(" ")[0])}.`:"Sua agenda está em dia."}</h2><p>${soon[0]?"Prepare a mensagem, confira a foto e não deixe a data passar.":"Cadastre aniversários para começar a receber lembretes."}</p><div class="stat-row"><div class="stat"><strong>${thisWeek.length}</strong><span>nos próximos 7 dias</span></div><div class="stat"><strong>${pending.length}</strong><span>pendências para revisar</span></div><div class="stat"><strong>${state.people.length}</strong><span>pessoas cadastradas</span></div></div></section><section class="card"><div class="section-title"><h2>Próximos aniversários</h2><button data-go="people">Ver agenda</button></div><div class="next-list">${soon.map(p=>`<div class="event"><div class="event-date"><b>${String(nextOccurrence(p).getDate()).padStart(2,"0")}</b>${nextOccurrence(p).toLocaleDateString("pt-BR",{month:"short"}).replace(".","")}</div>${personImage(p)}<main><strong>${esc(p.name)}</strong><small>${daysUntil(p)===0?"Hoje":daysUntil(p)===1?"Amanhã":`em ${daysUntil(p)} dias`}</small></main><span class="badge ${daysUntil(p)<=7?"alert":""}">${daysUntil(p)<=7?"avisar":"agenda"}</span></div>`).join("")}</div></section></div><section class="card" style="margin-top:20px"><div class="section-title"><h2>Pendências que impedem um card completo</h2><button data-go="people">Resolver agora</button></div><div class="pending-grid">${pending.length?pending.slice(0,6).map(p=>`<div class="pending-item"><span class="dot"></span>${personImage(p)}<div><strong>${esc(p.name)}</strong><small>${!p.photo?"Foto de busto pendente":""}${!p.photo&&!p.birthday?" · ":""}${!p.birthday?"Data de aniversário pendente":""}</small></div><button class="quiet-button edit-person" data-id="${p.id}">Completar</button></div>`).join(""):`<p class="empty">Tudo certo por aqui.</p>`}</div></section>`;}
function renderPeople(){const people=[...state.people].sort((a,b)=>a.name.localeCompare(b.name,"pt-BR"));$("#peopleView").innerHTML=`<div class="toolbar"><input class="search" id="searchPeople" placeholder="Buscar por nome, área ou status"/><button class="quiet-button" id="importPeople">Importar do Excel</button></div><div class="people-grid" id="peopleGrid">${people.map(personCard).join("")}</div>`;$("#searchPeople").oninput=e=>{const q=e.target.value.toLowerCase();$("#peopleGrid").innerHTML=people.filter(p=>`${p.name} ${p.team} ${status(p)}`.toLowerCase().includes(q)).map(personCard).join("");bindEdits();};$("#importPeople").onclick=()=>$("#importDialog").showModal();}
function personCard(p){return `<article class="person-card edit-person" data-id="${p.id}"><div class="person-photo">${personImage(p,"person-photo-image")}</div><div class="person-meta"><h3>${esc(p.name)}</h3><p>${p.team||"Sem área cadastrada"}</p><div class="status-row"><span class="badge ${p.photo&&p.birthday?"ready":"alert"}">${status(p)}</span><span>${p.birthday?dateLabel(nextOccurrence(p)):"—"}</span></div></div></article>`;}
function renderMessages(){const example=state.people.find(p=>p.name.includes("Castro"))||state.people[0];const options=state.people.filter(p=>p.name).sort((a,b)=>a.name.localeCompare(b.name,"pt-BR")).map(p=>`<option value="${p.id}" ${p.id===example.id?"selected":""}>${esc(p.name)}${p.photo?"":" · foto pendente"}</option>`).join("");$("#messagesView").innerHTML=`<div class="message-editor"><section class="card"><p class="eyebrow">TEXTO BASE DE ANIVERSÁRIO</p><label class="field-label">Mensagem editável<textarea id="birthdayTemplate" rows="7">${esc(state.messages.birthday)}</textarea></label><p class="notice">Use <strong>{nome}</strong> para inserir automaticamente o primeiro nome da pessoa.</p><button class="primary-button" id="saveMessages">Salvar texto padrão</button><div style="margin-top:26px"><p class="eyebrow">EXPORTAR CARD</p><label class="field-label">Pessoa do card<select id="cardPerson">${options}</select></label><div class="list-actions"><button class="primary-button" id="downloadCardPng">Baixar card PNG</button><button class="quiet-button" id="downloadCardSvg">Baixar versão SVG</button></div><p class="notice">PNG pronto para postar. SVG mantém a melhor qualidade e é a alternativa caso um link externo de foto bloqueie a exportação.</p></div></section><aside class="message-preview"><p class="eyebrow" style="color:#fff">PRÉVIA DO CARD</p><h2 id="cardHeading">Feliz aniversário,<br>${esc(example.name.split(" ")[0])}</h2><p id="messagePreview">${esc((state.messages.birthday||"").replace("{nome}",example.name.split(" ")[0]))}</p></aside></div>`;const person=()=>state.people.find(p=>p.id===$("#cardPerson").value)||example;const refresh=()=>{const p=person();$("#cardHeading").innerHTML=`Feliz aniversário,<br>${esc(p.name.split(" ")[0])}`;$("#messagePreview").textContent=$("#birthdayTemplate").value.replace("{nome}",p.name.split(" ")[0]);};$("#birthdayTemplate").oninput=refresh;$("#cardPerson").onchange=refresh;$("#saveMessages").onclick=()=>{state.messages.birthday=$("#birthdayTemplate").value;save();toast("Texto padrão atualizado");};$("#downloadCardPng").onclick=()=>downloadCardPng(person(),$("#birthdayTemplate").value);$("#downloadCardSvg").onclick=()=>downloadCardSvg(person(),$("#birthdayTemplate").value);}
function renderSettings(){const next=state.people.filter(p=>p.birthday).sort((a,b)=>daysUntil(a)-daysUntil(b));$("#settingsView").innerHTML=`<div class="settings-grid"><section class="card settings-card"><p class="eyebrow">LEMBRETES</p><h2>Um aviso com antecedência</h2><p>Ative notificações no navegador para receber o aviso ao abrir o painel. Para alertas mesmo com o navegador fechado, baixe os lembretes e importe no Google Agenda.</p><div class="list-actions"><button class="primary-button" id="askPermission">Ativar no navegador</button><button class="quiet-button" id="downloadIcs">Baixar lembretes .ics</button></div><p class="notice">Sites estáticos não conseguem disparar notificações com o navegador fechado. O arquivo .ics cria lembretes confiáveis no Google Agenda, 7 dias antes de cada aniversário.</p></section><section class="card settings-card"><p class="eyebrow">ACESSO</p><h2>Senha local</h2><p>Este modo mantém dados e uploads neste navegador. Para publicar com acesso real de várias pessoas, conecte um serviço de autenticação e armazenamento, como Supabase.</p><label>Nova senha<input id="newPassword" type="password" placeholder="Deixe vazio para não alterar"/></label><button class="quiet-button" id="changePassword" style="margin-top:14px">Salvar nova senha</button></section><section class="card settings-card"><p class="eyebrow">DADOS</p><h2>Banco local</h2><p>${state.people.length} colaboradores cadastrados. Você pode exportar uma cópia ou reiniciar a demonstração.</p><div class="list-actions"><button class="quiet-button" id="exportData">Exportar JSON</button><button class="quiet-button" id="resetData">Restaurar base inicial</button></div></section><section class="card settings-card"><p class="eyebrow">PRÓXIMO AVISO</p><h2>${next[0]?esc(next[0].name):"Sem aniversários"}</h2><p>${next[0]?`O aniversário é ${dateLabel(nextOccurrence(next[0]))}. O lembrete de uma semana ocorre em ${dateLabel(new Date(nextOccurrence(next[0]).getTime()-7*86400000))}.`:"Cadastre uma data para criar lembretes."}</p></section></div>`;bindSettings();}
function openPerson(id){editingId=id;const p=state.people.find(x=>x.id===id)||{name:"",birthday:"",team:"",photo:"",message:"",photoStatus:"pending"};$("#personFormLabel").textContent=id?"EDITAR COLABORADOR":"NOVO COLABORADOR";$("#personFormTitle").textContent=id?"Atualizar perfil":"Cadastrar pessoa";$("#personName").value=p.name;$("#personBirthday").value=p.birthday||"";$("#personTeam").value=p.team||"";$("#personPhotoStatus").value=p.photoStatus||"pending";$("#personPhotoUrl").value=p.photo||"";$("#personMessage").value=p.message||"";$("#personPhotoFile").value="";$("#personDialog").showModal();}
function bindEdits(){document.querySelectorAll(".edit-person").forEach(el=>el.onclick=()=>openPerson(el.dataset.id));}
function bindSettings(){$("#askPermission").onclick=askAlerts;$("#downloadIcs").onclick=downloadIcs;$("#changePassword").onclick=()=>{if($("#newPassword").value){state.password=$("#newPassword").value;save();$("#newPassword").value="";toast("Senha alterada");}};$("#exportData").onclick=()=>downloadFile("celebra-backup.json",JSON.stringify(state,null,2),"application/json");$("#resetData").onclick=()=>{if(confirm("Restaurar a base inicial? Dados e fotos enviados neste navegador serão removidos.")){state={people:seed,password:DEFAULT_PASSWORD,messages:state.messages};save();renderAll();}};}
function renderAll(){renderDashboard();renderPeople();renderMessages();renderSettings();$("#peopleCount").textContent=state.people.length;$("#todayLabel").textContent=new Date().toLocaleDateString("pt-BR",{weekday:"long",day:"numeric",month:"long"});bindEdits();document.querySelectorAll("[data-go]").forEach(b=>b.onclick=()=>selectView(b.dataset.go));}
function selectView(view){document.querySelectorAll(".view").forEach(v=>v.hidden=true);$(`#${view}View`).hidden=false;document.querySelectorAll(".nav-item").forEach(b=>b.classList.toggle("active",b.dataset.view===view));$("#viewTitle").textContent={dashboard:"Olá, vamos celebrar",people:"Colaboradores",messages:"Textos e cards",settings:"Configurações"}[view];}
function parseDate(value){const v=value.trim();if(/^\d{4}-\d{2}-\d{2}$/.test(v))return v;const m=v.match(/^(\d{1,2})[\/-](\d{1,2})[\/-](\d{2,4})$/);if(!m)return "";return `${m[3].length===2?`19${m[3]}`:m[3]}-${m[2].padStart(2,"0")}-${m[1].padStart(2,"0")}`;}
function toast(text){const t=document.createElement("div");t.textContent=text;t.style.cssText="position:fixed;right:24px;bottom:24px;background:#17122e;color:white;padding:13px 16px;border-radius:10px;font:600 13px var(--sans);box-shadow:0 15px 35px #17122e44;z-index:10";document.body.append(t);setTimeout(()=>t.remove(),2600);}
function askAlerts(){if(!("Notification" in window))return toast("Seu navegador não suporta notificações.");Notification.requestPermission().then(p=>toast(p==="granted"?"Alertas ativados neste navegador.":"Permissão não concedida."));}
function checkAlerts(){if(Notification.permission!=="granted")return;state.people.filter(p=>p.birthday&&daysUntil(p)===7).forEach(p=>new Notification("Aniversário em uma semana",{body:`Prepare o card de ${p.name}.`}));}
function downloadFile(name,data,type){const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([data],{type}));a.download=name;a.click();URL.revokeObjectURL(a.href);}
function cardFileName(person,extension){return `card-aniversario-${person.name.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/(^-|-$)/g,"")}.${extension}`;}
function cardSvg(person,template){const first=person.name.split(" ")[0];const message=(template||"").replace("{nome}",first).slice(0,180);const rawPhoto=asPhoto(person.photo);const photo=rawPhoto&&!/^(data:|https?:|blob:)/i.test(rawPhoto)?new URL(rawPhoto,document.baseURI).href:rawPhoto;const image=photo?`<image href="${esc(photo)}" x="74" y="76" width="932" height="570" preserveAspectRatio="xMidYMid slice" clip-path="url(#photoClip)"/>`:`<rect x="74" y="76" width="932" height="570" rx="42" fill="#e8e4ff"/><text x="540" y="370" text-anchor="middle" font-family="DM Sans, Arial, sans-serif" font-size="36" font-weight="700" fill="#5043b8">Foto de ${esc(first)}</text>`;return `<svg xmlns="http://www.w3.org/2000/svg" width="1080" height="1350" viewBox="0 0 1080 1350"><defs><clipPath id="photoClip"><rect x="74" y="76" width="932" height="570" rx="42"/></clipPath><linearGradient id="bg" x1="0" y1="0" x2="1" y2="1"><stop stop-color="#6150ef"/><stop offset="1" stop-color="#2f248e"/></linearGradient></defs><rect width="1080" height="1350" fill="url(#bg)"/><circle cx="1000" cy="122" r="240" fill="none" stroke="#ffffff" stroke-opacity=".13" stroke-width="38"/><circle cx="1008" cy="1230" r="350" fill="none" stroke="#ffffff" stroke-opacity=".10" stroke-width="50"/>${image}<text x="76" y="748" font-family="DM Sans, Arial, sans-serif" font-size="22" font-weight="700" letter-spacing="5" fill="#ded9ff">HIDROGEST CELEBRA</text><text x="76" y="860" font-family="DM Serif Display, Georgia, serif" font-size="82" fill="#ffffff">Feliz aniversário,</text><text x="76" y="958" font-family="DM Serif Display, Georgia, serif" font-size="98" fill="#ffffff">${esc(first)}</text><foreignObject x="76" y="1015" width="850" height="180"><div xmlns="http://www.w3.org/1999/xhtml" style="font-family:Arial,sans-serif;font-size:30px;line-height:1.4;color:#f5f3ff">${esc(message)}</div></foreignObject><text x="76" y="1280" font-family="DM Sans, Arial, sans-serif" font-size="22" letter-spacing="3" fill="#ded9ff">UM NOVO CICLO DE REALIZAÇÕES</text></svg>`;}
function downloadCardSvg(person,template){downloadFile(cardFileName(person,"svg"),cardSvg(person,template),"image/svg+xml;charset=utf-8");toast("Card SVG baixado");}
function downloadCardPng(person,template){const source=URL.createObjectURL(new Blob([cardSvg(person,template)],{type:"image/svg+xml;charset=utf-8"}));const image=new Image();const fallback=()=>{URL.revokeObjectURL(source);downloadCardSvg(person,template);toast("O link da foto bloqueou o PNG; baixamos o SVG em alta qualidade.");};image.onload=()=>{try{const canvas=document.createElement("canvas");canvas.width=1080;canvas.height=1350;canvas.getContext("2d").drawImage(image,0,0);URL.revokeObjectURL(source);canvas.toBlob(blob=>{if(!blob){fallback();return;}const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=cardFileName(person,"png");a.click();setTimeout(()=>URL.revokeObjectURL(a.href),200);toast("Card PNG baixado");},"image/png");}catch(error){fallback();}};image.onerror=fallback;image.src=source;}
function icsDate(date){return date.toISOString().slice(0,10).replaceAll("-","");}
function downloadIcs(){const now=new Date().toISOString().replace(/[-:]/g,"").replace(/\.\d{3}/,"");const events=state.people.filter(p=>p.birthday).map(p=>{const d=nextOccurrence(p);const stamp=icsDate(d);return `BEGIN:VEVENT\nUID:${p.id}@celebra.local\nDTSTAMP:${now}\nDTSTART;VALUE=DATE:${stamp}\nSUMMARY:Preparar aniversário de ${p.name}\nDESCRIPTION:Aniversário de ${p.name}. Prepare o card e a mensagem.\nBEGIN:VALARM\nTRIGGER:-P7D\nACTION:DISPLAY\nDESCRIPTION:Aniversário de ${p.name} em 7 dias\nEND:VALARM\nRRULE:FREQ=YEARLY\nEND:VEVENT`;}).join("\n");downloadFile("lembretes-aniversarios.ics",`BEGIN:VCALENDAR\nVERSION:2.0\nPRODID:-//Celebra//PT-BR\n${events}\nEND:VCALENDAR`,"text/calendar");toast("Arquivo de lembretes gerado");}
function setPhotoMode(mode){photoMode=mode;document.querySelectorAll(".tab").forEach(b=>b.classList.toggle("active",b.dataset.photoMode===mode));$("#linkPhoto").hidden=mode!=="link";$("#uploadPhoto").hidden=mode!=="upload";}
$("#loginDialog").showModal();$("#loginForm").addEventListener("submit",e=>{e.preventDefault();if($("#password").value===state.password){$("#loginDialog").close();$("#app").hidden=false;renderAll();checkAlerts();}else $("#loginError").textContent="Senha incorreta.";});
$("#signOut").onclick=()=>{$("#app").hidden=true;$("#password").value="";$("#loginDialog").showModal();};
document.querySelectorAll(".nav-item").forEach(b=>b.onclick=()=>selectView(b.dataset.view));$("#newPerson").onclick=()=>openPerson("");$("#enableAlerts").onclick=askAlerts;document.querySelectorAll(".tab").forEach(b=>b.onclick=()=>setPhotoMode(b.dataset.photoMode));
$("#personPhotoFile").onchange=e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>$("#personPhotoUrl").value=r.result;r.readAsDataURL(f);};
$("#personForm").addEventListener("submit",e=>{e.preventDefault();const record={id:editingId||`p${Date.now()}`,name:$("#personName").value.trim(),birthday:$("#personBirthday").value,team:$("#personTeam").value.trim(),photo:$("#personPhotoUrl").value.trim(),photoStatus:$("#personPhotoStatus").value,message:$("#personMessage").value.trim()};if(record.photo)record.photoStatus="ready";if(editingId)state.people=state.people.map(p=>p.id===editingId?record:p);else state.people.push(record);save();$("#personDialog").close();renderAll();toast("Perfil salvo");});
$("#importForm").addEventListener("submit",e=>{e.preventDefault();const lines=$("#bulkPaste").value.trim().split(/\r?\n/).filter(Boolean);let added=0;lines.forEach(line=>{const [name,date]=line.split(/\t|;/);if(!name)return;const birthday=parseDate(date||"");const exists=state.people.find(p=>p.name.toLowerCase()===name.trim().toLowerCase());if(exists){exists.birthday=birthday||exists.birthday;}else {state.people.push({id:`p${Date.now()}${added}`,name:name.trim(),birthday,team:"",photo:"",message:"",photoStatus:"pending"});added++;}});save();$("#importDialog").close();$("#bulkPaste").value="";renderAll();toast(`${added} novos registros importados`);});
